steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamlit-ml-demo', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/streamlit-ml-demo']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'streamlit-ml-demo',
        '--image', 'gcr.io/$PROJECT_ID/streamlit-ml-demo',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
      ]
images:
  - 'gcr.io/$PROJECT_ID/streamlit-ml-demo'
